-- person
CREATE TABLE person (
	person_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	name varchar(255) NULL,
    phone varchar(255) NULL,
    birth varchar(255) NULL,
	gender varchar(255) NULL,
    address1 varchar(255) NULL,
	address2 varchar(255) NULL,
    created_date timestamp(6) NULL,
	last_modified_date timestamp(6) NULL,
	CONSTRAINT person_pkey PRIMARY KEY (person_id)
);

-- users
CREATE TABLE users (
	id varchar(255) NOT NULL,
	name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
	password varchar(255) NULL,
	picture varchar(255) NULL,
	provider varchar(255) NOT NULL,
	role varchar(255) NOT NULL,
	CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['GUEST'::character varying, 'USER'::character varying, 'ADMIN'::character varying])::text[])))
);