name: PR Pipeline

on:
 pull_request:
   branches: 
     - main

jobs:
  # 개발 환경
  pull_request_build_test:
    runs-on: ubuntu-latest  
    environment: production
    steps:
    - 
      name: Checkout Repository
      uses: actions/checkout@v4

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  
      # Docker Buildx를 설정합니다.

    - 
      name: Build and Push
      uses: docker/build-push-action@v6
      with:
        # 빌드 컨텍스트 : Dockerfile이 있는 위치
        context: .
        # Dockerfile의 경로
        file: Dockerfile
        build-args: |
          PROFILE=${{ vars.PROFILE }}
          POSTGRESQL_POSTGRES_PASSWORD=${{secrets.POSTGRESQL_POSTGRES_PASSWORD}}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          TZ=${{ vars.TZ }}
          
        push: false  # 이미지를 레지스트리에 푸시합니다.